config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# Prefix Verb   URI Pattern               Controller#Action
# root GET    /                           tasks#index
# tasks GET    /tasks(.:format)           tasks#index
#       POST   /tasks(.:format)            tasks#create
# new_task GET    /tasks/new(.:format)     tasks#new
# edit_task GET    /tasks/:id/edit(.:format)   tasks#edit
# task GET    /tasks/:id(.:format)         tasks#show
# PATCH  /tasks/:id(.:format)              tasks#update
# PUT    /tasks/:id(.:format)              tasks#update
# DELETE /tasks/:id(.:format)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end
  # 登録アクション
  def create
    task = Task.new(task_params)
    task.save!
    redirect_to tasks_url
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update!(task_params)
    redirect_to tasks_url
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_url
  end

  private

  # taskモデルの
  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskleaf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<%= link_to '一覧', tasks_path %>

<%= form_with model: @task do |f| %>
  <div>
    <p><%= f.label :name %></p>
    <p><%= f.text_field :name %></p>
    <p><%= f.label :email %></p>
    <p><%= f.text_field :email %></p>
    <p><%= f.submit nil %></p>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p><%= link_to '新規登録', new_task_path %></p>

<div>
  <% @tasks.each do |task| %>
  <p>
    <%= link_to task.name, task_path(task) %>
    <%= link_to task.email, task_path(task) %>
    <%= link_to task.description, task_path(task) %>
  </p>
    <%= link_to '編集', edit_task_path(task) %>
    <%= link_to '削除', task, method: :delete %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<%= link_to '一覧', tasks_path %>

<%= form_with model: @task do |f| %>
  <div>
      <p><%= f.label :name %></p>
      <p><%= f.text_field :name %></p>
      <p><%= f.label :email %></p>
      <p><%= f.text_field :email %></p>
      <p><%= f.submit nil %></p>
  </div>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<%= link_to '一覧', tasks_path %>

<P><%= Task.human_attribute_name(:id) %></P>
<P><%= @task.id %></P>
<P><%= Task.human_attribute_name(:email) %></P>
<P><%= @task.email %></P>
<P><%= Task.model_name.human %></P>
<P><%= @task.description %></P>
<%= link_to '編集', edit_task_path %>
<%= link_to '削除', @task, method: :delete %>